#!/bin/bash

# [4]
# check-install: try to find out it installation was successful.

cc='riscv32-unknown-elf-gcc'
cxx='riscv32-unknown-elf-g++'

function check-cmd {
    name="${1}"
    command -v "${name}" >/dev/null 2>&1 ||
        (echo "${name}: command not found" && exit 1)
    echo "[OK] located ${name}"
}

function check-spike {
    mkdir -p build &&
        ${cc} data/hello.c -o build/cc_hello &&
        echo '[OK] C compiler works' &&
        ${cxx} data/hello.cpp -o build/cxx_hello &&
        echo '[OK] C++ compiler works' &&
        spike --isa=RV32IM "${RISCV_PK}" build/cc_hello &&
        spike --isa=RV32IM "${RISCV_PK}" build/cxx_hello &&
        echo '[OK] spike works'
}

check-cmd "${cc}" &&
    check-cmd "${cxx}" &&
    check-cmd 'spike' &&
    check-spike &&
    echo '[OK] done'
